---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start:
    present: false
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  brackets:
    max-spaces-inside: 1
