/// Authentication module with JWT token handling
pub mod auth;

/// API module with HTTP endpoints
pub mod api;

/// Shopping cart module with user isolation and inventory validation
pub mod cart;

/// Product catalog module with CRUD operations, inventory management, and filtering
pub mod catalog;

/// Database configuration and connection pooling
pub mod config;

/// Database entity models (users, products, carts, cart_items)
pub mod models;

/// Database schema definitions (generated by Diesel)
pub mod schema;

// Re-export main types for convenience
pub use auth::{create_token, validate_token, Claims};
pub use cart::CartService;
pub use catalog::{NewProduct, Product, ProductFilter, ProductService};
pub use config::{establish_connection_pool, DbConnection, Pool};
pub use models::{Cart, CartItem, NewCart, NewCartItem, NewUser, User};
