/// Product catalog module with CRUD operations, inventory management, and filtering
pub mod catalog;

/// Database configuration and connection pooling
pub mod config;

/// Database entity models (users, products, carts, cart_items)
pub mod models;

/// Database schema definitions (generated by Diesel)
pub mod schema;

// Re-export main types for convenience
pub use catalog::{NewProduct, Product, ProductFilter, ProductService};
pub use config::{establish_connection_pool, DbConnection, Pool};
pub use models::{Cart, CartItem, NewCart, NewCartItem, NewUser, User};
