/// Database configuration module.
///
/// This module provides database connection pooling functionality using
/// Diesel ORM and r2d2 connection pool.
pub mod config;

/// Database entity models.
///
/// This module defines all ORM model structs for database entities including
/// users, products, carts, and cart items. Each entity has both a queryable
/// struct (for reading from DB) and an insertable struct (for writing to DB).
pub mod models;

/// Database schema definitions.
///
/// This module is auto-generated by Diesel CLI and contains table definitions
/// and relationship macros. Do not edit manually - regenerate using `diesel migration run`.
pub mod schema;
